export const WEATHER_CONSTANTS = {
  APPLICATION: {
    REPOSITORY_TOKEN: Symbol('WEATHER_REPOSITORY_TOKEN'),
  },
  DOMAIN: {
    LATITUDE_MIN_VALUE: -90,
    LATITUDE_MAX_VALUE: 90,
    LONGITUDE_MIN_VALUE: -180,
    LONGITUDE_MAX_VALUE: 180,
  },
} as const;
